### PR TITLE
Modified the entity editor to support the editing of resource groups …

### PR DESCRIPTION
**Pull request by endoplasmicR**
…and selectors

This makes it easier to modify the resource groups and the selectors.

UI on dev:

example resource groups and editors can be found at https://trino.io/docs/current/admin/resource-groups.html
Screen Shot 2021-12-08 at 2 49 56 PM
Screen Shot 2021-12-08 at 2 50 06 PM
Screen Shot 2021-12-08 at 2 50 19 PM

### CODE REVIEW

**Comment by puneetjaiswal** [comment]
nice 👍

**Review by bearcage — APPROVED** [review]

**Review by Htiango — DISMISSED** [review]
LGTM

**Review by Htiango — APPROVED** [review]
LGTM

**Pull request merged**
