### PR TITLE
DATA-9792- Handle NPE

### PR DESCRIPTION
**Pull request by hitejinder**

### CODE REVIEW

**Comment by hitejinder** [comment]
/ptal (👀) @ssanthanam185 @bearcage @Htiango @endoplasmicR @nishantrayan

**Comment by endoplasmicR** [comment]
Do we need to log something? do we need to remove the `null` entries to save time for the next iterations? LGTM otherwise
/approve

**Comment by hitejinder** [comment]
@endoplasmicR logging isn't necessarily needed. It's just a simple null check. 

 /approve doesn't work in this repo. Can you explicitly mark it approved?

**Pull request merged**
