### PR TITLE
update gateway version to incorporate latest presto gateway api changes

### PR DESCRIPTION
**Pull request by riteshvaryani**
This PR updates the gateway version for latest presto gateway api changes

### CODE REVIEW

**Comment by riteshvaryani** [comment]
/ptal! @ssanthanam185 @Htiango @endoplasmicR #interactive-data-dev

**Comment by riteshvaryani** [comment]
ptal! @ssanthanam185 @Htiango @endoplasmicR #interactive-data-dev

**Comment by riteshvaryani** [comment]
PTAL! @ssanthanam185 @Htiango @endoplasmicR #interactive-data-dev

**Review by Htiango — APPROVED** [review]

**Comment by riteshvaryani** [comment]
thx

**Comment by riteshvaryani** [comment]
🚀

**Pull request merged**
